apiVersion: apps/v1
kind: Deployment
metadata:
  name: cukectrl
  namespace: cukectrl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cukectrl
  template:
    metadata:
      labels:
        app: cukectrl
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: cukectrl
          image: ghcr.io/miuzaki/cukectrl:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cukectrl-env
